config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :plants do
    resources :measurements, :schedules, :settings
  end

  resources :devices
  resources :users
  resources :setting_sets

  namespace :api, defaults: { format: :json } do
    resources :measurements, only: [:index, :create] do
      member do
        post :create
      end
    end
  end

  root 'plants#index'
end

app/models/device.rb
class Device < ApplicationRecord
  has_many :plants, dependent: :delete_all
  belongs_to :user

  validates :name, presence: true
  validates :uri_address, presence: true
  validates :user_id, presence: true
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate_user!

  def index
    @devices = Device.all
  end

  def show
    @device = Device.find(params[:id])
  end

  def new
    @device = Device.new
  end

  def create
    @user = current_user
    @device = @user.devices.create(device_params)

    if @device.save
      redirect_to @device
    else
      render 'new'
    end
  end

  def edit
    @device = Device.find(params[:id])
  end

  def update
    @device = Device.find(params[:id])

    if @device.update(device_params)
      redirect_to @device
    else
      render 'edit'
    end
  end

  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    redirect_to devices_path
  end

  private

  def device_params
    params.require(:device).permit(:name, :user_id, :uri_address)
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/edit.html.erb
<h1>Edit device</h1>

<%= form_with(model: @device, local: true) do |form| %>

  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@device.errors.count, "error") %> prohibited
        this device from being saved:
      </h2>
      <ul>
        <% @device.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :uri_address %><br>
    <%= form.text_field :uri_address %>
  </p>

  <p>
    <%= form.submit "Update Device", style: "color:white" ,class:"btn btn-primary" %>
  </p>
<% end %>

<button class="btn btn-secondary"><%= link_to 'Back', devices_path, style: "color:white"   %></button>

app/views/devices/index.html.erb
<h1>Available devices</h1>
<p>List of devices, choose which one you want to check</p>
<% @devices.each do |t| %>
  <p>
    <p style="font-size: x-large; color:darkblue"><%= t.name %></p>
    <button class="btn btn-primary"><%= link_to 'Show', device_path(t.id), style: "color:white" %></button>
    <button class="btn btn-primary"><%= link_to 'Edit', edit_device_path(t.id), style: "color:white" %></button>
    <button class="btn btn-primary"><td><%= link_to 'Destroy', device_path(t.id),
                  method: :delete, data: { confirm: 'Confirm removal of this device' }, style: "color:white" %></td></button>
  </p>
<% end %>


<p><button class="btn btn-secondary"><%= link_to 'Add new device', new_device_path, style: "color:white"   %></button></p>
<button class="btn btn-secondary"><%= link_to 'Back', plants_path, style: "color:white"   %></button>

app/views/devices/new.html.erb
<h1>Add new device</h1>

<%= form_with scope: :device, url: devices_path, local: true do |form| %>

  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@device.errors.count, "error") %> prohibited
        this device from being saved:
      </h2>
      <ul>
        <% @device.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :uri_address %><br>
    <%= form.text_field :uri_address %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p>
  <strong>Device:</strong>
  <%= @device.name %>
</p></br>
<p>
  <strong>URI Address:</strong>
  <%= @device.uri_address %>
</p>
<p>
  <strong>Plants monitored by this device:</strong>
  <% @device.plants.each do |plant| %>
    <p>
      <%= plant.name %>
      <button class="btn btn-outline-secondary"><%= link_to 'Show', plant_path(plant.id)%></button>
    </p>
  <% end %>
</p>

<button class="btn btn-secondary"><%= link_to 'Back', devices_path, style: "color:white"   %></button>