config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :plants do
    resources :measurements, :schedules, :settings
  end

  resources :devices
  resources :users
  resources :setting_sets

  namespace :api, defaults: { format: :json } do
    resources :measurements, only: [:index, :create] do
      member do
        post :create
      end
    end
  end

  root 'plants#index'
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_one :schedule, dependent: :destroy
  has_one :setting, dependent: :destroy
  has_many :measurements, dependent: :destroy
  belongs_to :device
  belongs_to :user
  has_many_attached :photos

  validates :name, presence: true, allow_blank: false
  validates :device_id, presence: true
  validates :user_id, presence: true
  validate :photo_type

  private
  def photo_type
    photos.each do |photo|
      unless photo.content_type.in?(%('image/jpeg' image/png'))
        errors.add(:photos, 'needs to be a JPEG or PNG')
      end
    end
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :authenticate_user!

  def index
    @plants = current_user.plants.all
  end

  def show
    @plant = Plant.find(params[:id])
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant = current_user.plants.new(plant_params)

    if @plant.save
      redirect_to @plant
    else
      render 'new'
    end
  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])

    if @plant.update(plant_params)
      redirect_to @plant
    else
      render 'edit'
    end
  end
  
  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    redirect_to plants_path
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :device_id, photos: [])
  end

end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/edit.html.erb
<h1>Edit plant</h1>

<%= form_with(model: @plant, local: true) do |form| %>
  <p class="form-group">
    <% if @plant.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@plant.errors.count, "error") %> prohibited
          this plant from being saved:
        </h2>
        <ul>
          <% @plant.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= form.label :name, style: "font-size: x-large; color: darkblue" %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :photos, style: "font-size: x-large; color: darkblue" %><br>
      <%= form.file_field :photos, multiple: true, style: "color:white" ,class:"btn btn-primary"  %>
    </p>

    <p>
      <%= form.submit "Update Plant", style: "color:white" ,class:"btn btn-primary" %>
    </p>
  </div>
<% end %>

<button class="btn btn-secondary"><%= link_to 'Back', plants_path, style: "color:white"   %></button>

app/views/plants/index.html.erb
<h1>Your plants</h1>
<% if @plants %>
  <% @plants.each do |plant| %>
  <p><p style="font-size: x-large; color:darkblue"><%= plant.name %>:</p>
      <button class="btn btn-primary"><%= link_to 'Show', plant_path(plant.id), style: "color:white" %></button>
      <button class="btn btn-primary"><%= link_to 'Edit', edit_plant_path(plant.id), style: "color:white" %></button>
      <button class="btn btn-primary"><%= link_to 'Destroy', plant_path(plant.id),
                    method: :delete,
                      data: { confirm: 'Confirm removal of this plant' }, style: "color:white"  %></button>
      <button class="btn btn-primary"><%= link_to 'Measurements', plant_measurements_path(plant.id), style: "color:white"  %></button>
      <% if plant.setting %>
        <button class="btn btn-primary"><%= link_to 'Plant settings', plant_setting_path(plant.id, plant.setting.id), style: "color:white"  %></button>
      <% else %>
        <button class="btn btn-primary"><%= link_to 'Plant settings', new_plant_setting_path(plant.id), style: "color:white"  %></button>
      <% end %>
      <% if plant.schedule %>
        <button class="btn btn-primary"><%= link_to 'Watering schedule', plant_schedule_path(plant.id, plant.schedule.id), style: "color:white"  %></button>
      <% else %>
        <button class="btn btn-primary"><%= link_to 'Watering schedule', new_plant_schedule_path(plant.id), style: "color:white"  %></button>
      <% end %>
      <button class="btn btn-primary"><%= link_to "Device: #{plant.device.name}", device_path(plant.device_id), style: "color:white"  %></button>
    </p>
  <% end %>
<% end %>

<button class="btn btn-secondary"><%= link_to 'Add new plant', new_plant_path, style: "color:white"  %></button>

app/views/plants/new.html.erb
<h1>Add new plant if you wish</h1>

<%= form_with scope: :plant, url: plants_path, local: true do |form| %>

  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@plant.errors.count, "error") %> prohibited
        this plant from being saved:
      </h2>
      <ul>
        <% @plant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :device_id %><br>
    <%= form.select :device_id, options_for_select(Device.where(user_id: current_user.id).collect { | device| [device.name, device.id] }, @device), {}, {} %>
  </p>

  <div class="field">
    <%= form.label :photos %>
    <%= form.file_field :photos, multiple: true %>
  </div>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<button class="btn btn-secondary"><%= link_to 'Back', plants_path, style: "color:white"   %></button>

app/views/plants/show.html.erb
<p>
  <strong>Name of monitored plant:</strong>
  <%= @plant.name %>
</p>
<% if @plant.schedule&.watering %>
  <p>
    <strong>Watering schedule interval:</strong>
    <%= @plant.schedule.interval %>
  </p>
<% end %>
<% if @plant.setting&.single_watering_amount %>
  <p>
    <strong>Amount of water per single watering:</strong>
    <%= @plant.setting.single_watering_amount %>
  </p>
<% end %>

<% @plant.photos.each do |photo| %>
  <%= image_tag photo, width:300, height:300  %>
<% end %><br>


<button class="btn btn-secondary"><%= link_to 'Back', plants_path, style: "color:white"   %></button>