config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :plants do
    resources :measurements, :schedules, :settings
  end

  resources :devices
  resources :users
  resources :setting_sets

  namespace :api, defaults: { format: :json } do
    resources :measurements, only: [:index, :create] do
      member do
        post :create
      end
    end
  end

  root 'plants#index'
end

app/models/setting_set.rb
class SettingSet < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, allow_blank: false
end

app/controllers/setting_sets_controller.rb
class SettingSetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @setting_sets = SettingSet.all
  end

  def show
    @setting_set = SettingSet.find(params[:id])
  end

  def new
    @setting_set = SettingSet.new
  end

  def create
    @setting_set = SettingSet.new(setting_sets_params)

    if @setting_set.save
      p setting_sets_params
      redirect_to setting_sets_path
    else
      render 'new'
    end
  end

  def edit
    @setting_set = SettingSet.find(params[:id])
  end

  def update
    @setting_set = SettingSet.find(params[:id])

    if @setting_set.update(setting_sets_params)
      redirect_to @setting_set
    else
      render 'edit'
    end
  end

  def destroy
    @setting_set = SettingSet.find(params[:id])
    @setting_set.destroy

    redirect_to setting_sets_path
  end

  private

  def setting_sets_params
    params.require(:setting_set).permit(:name,
                                       :single_watering_amount,
                                       :min_air_humidity,
                                       :max_air_humidity,
                                       :min_soil_moisture,
                                       :max_soil_moisture,
                                       :min_temperature,
                                       :max_temperature,
                                       :max_insolation,
                                       :min_water_amount)
  end

end

app/views/setting_sets/edit.html.erb
<h1>Change setting set</h1>
<%= form_with scope: :setting_set, url: setting_sets_path, local: true do |setting_set| %>
  <%= setting_set.label :name %>
  <%= setting_set.text_field :name  %><br>
  <%= setting_set.label :single_watering_amount %>
  <%= setting_set.number_field :single_watering_amount %><br>
  <%= setting_set.label :min_air_humidity %>
  <%= setting_set.number_field :min_air_humidity %><br>
  <%= setting_set.label :max_air_humidity %>
  <%= setting_set.number_field :max_air_humidity %><br>
  <%= setting_set.label :min_soil_moisture %>
  <%= setting_set.number_field :min_soil_moisture %><br>
  <%= setting_set.label :max_soil_moisture %>
  <%= setting_set.number_field :max_soil_moisture %><br>
  <%= setting_set.label :min_temperature %>
  <%= setting_set.number_field :min_temperature %><br>
  <%= setting_set.label :max_temperature %>
  <%= setting_set.number_field :max_temperature %><br>
  <%= setting_set.label :max_insolation %>
  <%= setting_set.number_field :max_insolation %><br>
  <%= setting_set.label :min_water_amount %>
  <%= setting_set.number_field :min_water_amount %><br>

  <%= setting_set.submit %>
<% end %>

<%= link_to 'Back', setting_sets_path %>

app/views/setting_sets/index.html.erb
<h1>Available sets of settings for plants</h1>
<% @setting_sets.each do |t| %>
  <p>
    <p style="font-size: x-large; color:darkblue"><%= t.name %></p>
    <button class="btn btn-primary"><%= link_to 'Show', setting_set_path(t.id), style: "color:white"  %></button>
    <button class="btn btn-primary"><%= link_to 'Edit', edit_setting_set_path(t.id), style: "color:white"  %></button>
        <button class="btn btn-primary"><td><%= link_to 'Destroy', setting_set_path(t.id),
                    method: :delete, data: { confirm: 'Confirm removal of this set' }, style: "color:white"  %></td></button>
  </p>
<% end %>


<button class="btn btn-secondary"><%= link_to 'Add new set', new_setting_set_path, style: "color:white"   %></button>
<button class="btn btn-secondary"><%= link_to 'Back', plants_path, style: "color:white"   %></button>

app/views/setting_sets/new.html.erb
<h1>Create settings set that can be used to define settings for plant</h1>
<p>Choose those settings that you are interested in. All of them are optional</p>
<%= form_with scope: :setting_set, url: setting_sets_path, local: true do |setting_set| %>
  <%= setting_set.label :name %>
  <%= setting_set.text_field :name  %><br>
  <%= setting_set.label :single_watering_amount %>
  <%= setting_set.number_field :single_watering_amount %><br>
  <%= setting_set.label :min_air_humidity %>
  <%= setting_set.number_field :min_air_humidity %><br>
  <%= setting_set.label :max_air_humidity %>
  <%= setting_set.number_field :max_air_humidity %><br>
  <%= setting_set.label :min_soil_moisture %>
  <%= setting_set.number_field :min_soil_moisture %><br>
  <%= setting_set.label :max_soil_moisture %>
  <%= setting_set.number_field :max_soil_moisture %><br>
  <%= setting_set.label :min_temperature %>
  <%= setting_set.number_field :min_temperature %><br>
  <%= setting_set.label :max_temperature %>
  <%= setting_set.number_field :max_temperature %><br>
  <%= setting_set.label :max_insolation %>
  <%= setting_set.number_field :max_insolation %><br>
  <%= setting_set.label :min_water_amount %>
  <%= setting_set.number_field :min_water_amount %><br>

  <%= setting_set.submit %>
<% end %>

<button class="btn btn-secondary"><%= link_to 'Back', setting_sets_path, style: "color:white"   %></button>

app/views/setting_sets/show.html.erb
<h1>Setting set</h1>
<p>Set: <%= @setting_set.name %></p>

<p>Amount of water in mL per single watering:
  <%= @setting_set&.single_watering_amount %></p>
<p>Minimum air humidity:
  <%= @setting_set&.min_air_humidity %></p>
<p>Maximum air humidity:
  <%= @setting_set&.max_air_humidity %></p>
<p>Minimum soil moisture:
  <%= @setting_set&.min_soil_moisture %></p>
<p>Maximum soil moisture:
  <%= @setting_set&.max_soil_moisture %></p>
<p>Minimum temperature:
  <%= @setting_set&.min_temperature %></p>
<p>Maximum temperature:
  <%= @setting_set&.max_temperature %></p>
<p>Maximum insolation:
  <%= @setting_set&.max_insolation %></p>
<p>Minimal amount of water in container:
  <%= @setting_set&.min_water_amount %></p>

<button class="btn btn-secondary"><%= link_to 'Edit', edit_setting_set_path(@setting_set), style: "color:white"   %></button>
<button class="btn btn-secondary"><%= link_to 'Back', setting_sets_path, style: "color:white"   %></button>