config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :plants do
    resources :measurements, :schedules, :settings
  end

  resources :devices
  resources :users
  resources :setting_sets

  namespace :api, defaults: { format: :json } do
    resources :measurements, only: [:index, :create] do
      member do
        post :create
      end
    end
  end

  root 'plants#index'
end

app/views/layouts/_navbar.html.erb
<header>
  <div class="navbar navbar-fixed-top">
    <h3><strong><%= link_to "PlantWatch", root_path %></strong></h3>
      <nav>
        <div class="float-end">
          <ul>
            <li><button class="btn btn-success"><%= link_to "Plants", plants_path %></button></li>
            <li><button class="btn btn-success"><%= link_to "Devices", devices_path %></button></li>
            <li><button class="btn btn-success"><%= link_to "Setting Sets", setting_sets_path %></button></li>
            <% if user_signed_in? %>
              <li><button class="btn btn-success"><%= link_to "Log out", destroy_user_session_path, method: :delete %></button></li>
            <% else %>
              <li><button class="btn btn-success"><%= link_to "Log in", new_user_session_path %></button></li>
              <li><button class="btn btn-success"><%= link_to "Sign up", new_user_registration_path %></button></li>
            <% end %>
          </ul>
        </div>
      </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plantwatch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<!--    <p class="notice"><%#= notice %></p>-->
<!--    <p class="alert"><%#= alert %></p>-->
    <canvas id = 'c', style="position:fixed; z-index: -5"></canvas>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <%= yield %>
  </body>
</html>